{
 "title": "Backups",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Most recent backups",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "borg_backup_sched_result{exported_job=\"borg_backup_sched\"}"
    },
    {
     "expr": "time() - push_time_seconds{exported_job=\"borg_backup_sched\"}"
    }
   ]
  },
  {
   "title": "Backup result trend",
   "type": "graph",
   "description": "Backup codes: 0 = OK, 1 = WARN, 2 = FAIL",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Backup Code" }
   ],
   "targets": [
    {
     "expr": "borg_backup_sched_result{exported_job=\"borg_backup_sched\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Backup size",
   "type": "graph",
   "description": "Total size of the backup repository",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "borg_backup_sched_size{exported_job=\"borg_backup_sched\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Backup duration",
   "type": "graph",
   "description": "Time required to create the backup",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "borg_backup_sched_duration{exported_job=\"borg_backup_sched\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}